name: backend-ci

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
      # email:
        # default: 'unknown@example.com' # used to mark ownership of the run from strapi

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, World!"

